apiVersion: v1
kind: Service
metadata:
  name: jogos-api-service
  namespace: default
  labels:
    app: jogos-api
spec:
  type: LoadBalancer
  selector:
    app: jogos-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
